---
- name: Import database.yml
  template:
    src: rokes/rails/templates/database.yml.j2
    dest: /var/www/raisetech-live8-sample-app/config/database.yml.j2
    owner: ec2-user
    group: ec2-user
