---
- name: Import database.yml
  vars:
    rds_endpoint: RDS_ENDPOINT
  template:
    src: roles/database/templates/database.yml.j2
    dest: /var/www/raisetech-live8-sample-app/config/database.yml
    owner: ec2-user
    group: ec2-user
