---
- name: Set up custom environment variable "RDS_ENDPOINT"
  shell: |
    var1=$(aws cloudformation describe-stacks --region ap-northeast-1 --stack-name RDSStackFromCircleCI --query "Stacks[].Outputs[].[OutputValue]" --output text)
    echo 'export RDS_ENDPOINT="$VAR1"' >> $BASH_ENV

- name: Import database.yml
  template:
    src: rokes/rails/templates/database.yml.j2
    dest: /var/www/raisetech-live8-sample-app/config/database.yml.j2