AWSTemplateFormatVersion: '2010-09-09'
Description: Security Layer Template

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Listener 3306
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: RDS Security Group

Outputs:
  SGforRDS:
    Description: Security Group for RDS
    Value: !Ref RDSSecurityGroup
    Export:
      Name: RDS-SecurityGroup