version: 2.1
executors:
  deploy_container:
    docker:
      - image: circleci/python:3.8.7
    working_directory: ~/work

orbs:
  aws-cli: circleci/aws-cli@1.3.2

commands:
  lint_and_unit_test:
    steps:
      - run:
          name: lint and unit test
          command: |
            set -x

            echo "any lint and unit test command"

  deploy:
    steps:
      - run:
          name: deploy
          command: |
            set -x

            aws --version

            echo "any deploy command"

            aws s3 ls

jobs:
  lint_and_unit_test:
    executor: deploy_container
    steps:
      - checkout
      - lint_and_unit_test

  deploy:
    executor: deploy_container
    steps:
      - checkout
      - aws-cli/install
      - deploy

workflows:
  version: 2
  release-workflow:
    jobs:
      - lint_and_unit_test:
          filters:
            tags:
              only: /.*/
      - deploy:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
          requires:
            - lint_and_unit_test