version: 2.1
executors:
  deploy_container:
    docker:
      - image: circleci/python:3.8.7
    working_directory: ~/work

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: deploy Cloudformation
          command: |
            set -x
            aws cloudformation deploy --stack-name NetworkStackFromCircleCI --template-file cloudformation/Network_template.yml

            aws cloudformation wait stack-create-complete --stack-name NetworkStackFromCircleCI 
            aws cloudformation deploy --stack-name SecurityGroupStackFromCircleCI --template-file cloudformation/SecurityGroup_template.yml

            aws cloudformation wait stack-create-complete --stack-name SecurityGroupStackFromCircleCI            
            aws cloudformation deploy --stack-name EC2andS3StackFromCircleCI --template-file cloudformation/EC2_S3_template.yml          
            aws cloudformation deploy --stack-name RDSStackFromCircleCI --template-file cloudformation/RDS_template.yml

            aws cloudformation wait stack-create-complete --stack-name EC2andS3StackFromCircleCI
            aws cloudformation deploy --stack-name ALBFromCircleCI --template-file cloudformation/ALB_template.yml

          no_output_timeout: 15m


workflows:
  raisetech-task-final:
    jobs:
      - execute-cloudformation