---
- name: Install wget
  yum:  
    name: wget
    state: present

- name: Create yarn repo
  template:
    src: roles/yarn/templates/yarn.repo.j2
    dest: /etc/yum.repos.d/yarn.repo

- name: Install yarn
  yum:
    name: yarn
    state: present