---
- name: Install bundler
  shell: bash -lc "gem install bundler:2.3.15"
  args: 
    chdir: /var/www/raisetech-live8-sample-app

- name: Install Rails
  shell: bash -lc "gem install rails -v 6.1.3"
  args: 
    chdir: /var/www/raisetech-live8-sample-app

# mysqlをインストールする際にGPGキーが必要となる。
# これをrpm_keyモジュールを使用してインポートする。
- name: Import RPM-GPG-KEY-mysql-2022
  become: yes
  rpm_key: 
    key: "https://repo.mysql.com/RPM-GPG-KEY-mysql-2022"

- name: Install mysql
  become: yes
  yum:
    name: mysql
    state: present

- name: Install mysql
  become: yes
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
    state: present

- name: Install mysql-community-devel
  become: yes
  yum:
    name: mysql-community-devel
    state: present

- name: Install mysql-community-server
  become: yes
  yum:
    name: mysql-community-server
    state: present

- name: bundle install
  shell: bash -lc "bundle install"
  args: 
    chdir: /var/www/raisetech-live8-sample-app

- name: Embed config/master.key
  vars:
    vars_files: roles/database/rails/vars/main.yml
  shell: echo {{ master_key }} > config/master.key
  args:
    chdir: /var/www/raisetech-live8-sample-app

# conflictを避けるため、デフォルトのwebpacker.ymlを削除
- name: delete config/webpacker.yml
  file:
    path: config/webpacker.yml
    state: absent

- name: Install config/webpacker.yml
  shell: bash -lc "bundle exec rails webpacker:install RAILS_ENV{{'='}}production"
  args: 
    chdir: /var/www/raisetech-live8-sample-app