---
- name: Install Gem
  shell: bash -lc "gem install bundle"
  args: 
    chdir: /var/www/raisetech-live8-sample-app

- name: Install Rails
  shell: bash -lc "gem install rails -v 6.1.3"
  args: 
    chdir: /var/www/raisetech-live8-sample-app

- name: bundle install
  shell: bash -lc "bundle install"
  args: 
    chdir: /var/www/raisetech-live8-sample-app

- name: install MySQL client
  yum:
    name: mysql
    state: latest

