---
- name: Make a directory for Rails app
  file:
    path: /var/www/raisetech-live8-sample-app
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "775"

- name: Clone git repository
  git:
    repo: https://github.com/tomohiro-tanazawa/raisetech-live8-sample-app.git
    dest: /var/www/raisetech-live8-sample-app

- name: chown recurse
  shell: chown ec2-user:ec2-user -R /var/www/raisetech-live8-sample-app