- name: Install yum-utils
  yum:
    name: yum-utils
    state: present

- name: Create Nginx repo
  template:
    src: roles/nginx/templates/nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: "Create /etc/nginx/conf.d/raisetech-live8-sample-app.conf"
  vars:
    vars_files: roles/nginx/vars/main.yml
  template:
    src: roles/nginx/templates/raisetech-live8-sample-app.conf.j2
    dest: /etc/nginx/conf.d/raisetech-live8-sample-app.conf

- name: Auto start Nginx
  shell: bash -lc "systemctl enable nginx.service"
