---
- hosts: ec2
  become: yes
  roles:
    - { role: git, tags: git }
    - { role: nodejs, tags: nodejs }
    - { role: nginx, tags: nginx }
    - { role: ruby, tags: ruby }
    - { role: git_clone, tags: git_clone }
    - { role: rails, tags: rails }
    - { role: database, tags: database }
